x-common-env: &common-env
  ASPNETCORE_ENVIRONMENT: Development

services:
  carrier-income-api:
    image: carrier-income-api
    build:
      context: ./
      dockerfile: "./src/CarrierIncomeApi/${DOCKERFILENAME:-Dockerfile}"
      args:
        - CONFIGURATION=Debug
    hostname: "${DOCKER_HOSTNAME:-localhost}"
    ports:
      - "5100:8080"
    environment:
      <<: *common-env
      ASPNETCORE_URLS: http://*:8080
    develop:
      watch:
        - action: rebuild
          path: ./src/CarrierIncomeApi

  consumer-income-api:
    image: consumer-income-api
    build:
      context: ./
      dockerfile: "./src/ConsumerIncomeApi/${DOCKERFILENAME:-Dockerfile}"
      args:
        - CONFIGURATION=Debug
    hostname: "${DOCKER_HOSTNAME:-localhost}"
    ports:
      - "5200:8080"
    environment:
      <<: *common-env
      ASPNETCORE_URLS: http://*:8080
    develop:
      watch:
        - action: rebuild
          path: ./src/ConsumerIncomeApi

  # consumer-web-app:
  #   image: consumer-web-app
  #   build:
  #     context: ./src/consumer-web-app/
  #     dockerfile: "./${DOCKERFILENAME:-Dockerfile}"
  #   hostname: "${DOCKER_HOSTNAME:-localhost}"
  #   ports:
  #     - "5300:3000"
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./src/consumer-web-app
